.publish-apt:
  image: registry.gitlab.com/passbolt/passbolt-ops/passbolt-aptly
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
  dependencies:
    - build-debian
  script:
    - |
      source .gitlab-ci/scripts/bin/set-env.sh "$CI_COMMIT_TAG"
      if $PASSBOLT_PUBLISH; then
        export PREFIX=$PASSBOLT_FLAVOUR/$DISTRIBUTION_REPO_DIR
        cd api && /publisher.sh
        bash ../.gitlab-ci/scripts/bin/slack-status-messages.sh ":rocket: $API_CLONE_BRANCH $PASSBOLT_FLAVOUR $PASSBOLT_COMPONENT $DISTRIBUTION_REPO_DIR package has been published" "$CI_PROJECT_URL/-/jobs/$CI_JOB_ID"
      else
        echo "THIS IS A TESTING RELEASE, NOT PUBLISHING"
      fi
  retry:
    max: 0

publish-debian:
  extends: .publish-apt
  variables:
    DISTRIBUTION: buster
    DISTRIBUTION_REPO_DIR: debian
  needs:
    - job: "debian-bookworm-runtime"
    - job: "debian-bookworm-purge"
    - job: "debian-bookworm-fs"
    - job: "build-debian"

publish-ubuntu:
  extends: .publish-apt
  variables:
    DISTRIBUTION: focal
    DISTRIBUTION_REPO_DIR: ubuntu
  needs:
    - job: "ubuntu-2404-runtime"
    - job: "ubuntu-2404-purge"
    - job: "ubuntu-2404-fs"
    - job: "build-debian"
