publish-yum-el8:
  extends: .publish-rpm
  variables:
    PACKAGE_PATH: "passbolt"
  needs:
    - job: "almalinux-9-runtime"
    - job: "almalinux-9-purge"
    - job: "almalinux-9-fs"
    - job: "rockylinux-9-runtime"
    - job: "rockylinux-9-purge"
    - job: "rockylinux-9-fs"
    - job: build-yum
      artifacts: true

publish-suse:
  extends: .publish-rpm
  variables:
    EL_VERSION: "opensuse"
    PACKAGE_PATH: "passbolt"
  needs:
    - job: "opensuse-leap-15-runtime"
    - job: "opensuse-leap-15-purge"
    - job: "opensuse-leap-15-fs"
    - job: build-suse
      artifacts: true
