publish-yum-el8:
  extends: .publish-rpm
  variables:
    PACKAGE_PATH: "passbolt"
  needs:
    - job: "almalinux-8-runtime"
    - job: "almalinux-8-purge"
    - job: "almalinux-8-fs"
    - job: "almalinux-9-runtime"
    - job: "almalinux-9-purge"
    - job: "almalinux-9-fs"
    - job: "fedora-39-runtime"
    - job: "fedora-39-purge"
    - job: "fedora-39-fs"
    - job: "fedora-40-runtime"
    - job: "fedora-40-purge"
    - job: "fedora-40-fs"
    - job: "oraclelinux-8-runtime"
    - job: "oraclelinux-8-purge"
    - job: "oraclelinux-8-fs"
    - job: "rockylinux-8-runtime"
    - job: "rockylinux-8-purge"
    - job: "rockylinux-8-fs"
    - job: "rockylinux-9-runtime"
    - job: "rockylinux-9-purge"
    - job: "rockylinux-9-fs"
    - job: build-yum
      artifacts: true

publish-suse:
  extends: .publish-rpm
  variables:
    EL_VERSION: "opensuse"
    PACKAGE_PATH: "passbolt"
  needs:
    - job: "opensuse-leap-15-runtime"
    - job: "opensuse-leap-15-purge"
    - job: "opensuse-leap-15-fs"
    - job: build-suse
      artifacts: true
