publish-yum-el8:
  extends: .publish-rpm
  variables:
    PACKAGE_PATH: "passbolt"
  needs:
    - job: "almalinux-8-runtime"
    - job: "almalinux-8-purge"
    - job: "almalinux-8-fs"
    - job: "fedora-38-runtime"
    - job: "fedora-38-purge"
    - job: "fedora-38-fs"
    - job: "oraclelinux-8-runtime"
    - job: "oraclelinux-8-purge"
    - job: "oraclelinux-8-fs"
    - job: "rockylinux-8-runtime"
    - job: "rockylinux-8-purge"
    - job: "rockylinux-8-fs"
    - job: "rockylinux-9-runtime"
    - job: "rockylinux-9-purge"
    - job: "rockylinux-9-fs"
    - job: build-yum
      artifacts: true

publish-yum-el7:
  extends: .publish-rpm
  variables:
    EL_VERSION: "el7"
    PACKAGE_PATH: "passbolt"
  needs:
    - job: "centos-7-runtime"
    - job: "centos-7-purge"
    - job: "centos-7-fs"
    - job: build-yum-7
      artifacts: true

publish-suse:
  extends: .publish-rpm
  variables:
    EL_VERSION: "opensuse"
    PACKAGE_PATH: "passbolt"
  needs:
    - job: "opensuse-leap-15-runtime"
    - job: "opensuse-leap-15-purge"
    - job: "opensuse-leap-15-fs"
    - job: build-suse
      artifacts: true
