default:
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - api_failure
      - stale_schedule

image: registry.gitlab.com/passbolt/passbolt-ci-docker-images/alpine-3.16

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - ci-scripts-tests
  - version-management
  - package-deps
  - package-build
  - package-tests
  - publish
  - publish-artifacts

include:
  - local: '/.gitlab-ci/Jobs/artifact_build.yml'
  - local: '/.gitlab-ci/Jobs/debian_package_build.yml'
  - local: '/.gitlab-ci/Jobs/packages_tests.yml'
  - local: '/.gitlab-ci/Jobs/rpm_package_build.yml'
  - local: '/.gitlab-ci/Jobs/ci_scripts_tests.yml'
  - local: '/.gitlab-ci/Jobs/version_management.yml'
