default:
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - api_failure
      - stale_schedule

image: alpine:latest

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - package-deps
  - package-build
  - package-tests
  - publish
  - publish-artifacts

include:
  - local: '/.gitlab-ci/Jobs/artifact_build.yml'
  - local: '/.gitlab-ci/Jobs/debian_package_build.yml'
  - local: '/.gitlab-ci/Jobs/packages_tests.yml'
  - local: '/.gitlab-ci/Jobs/rpm_package_build.yml'

code_quality:
  stage: unit-test
