default:
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - api_failure
      - stale_schedule

image: registry.gitlab.com/passbolt/passbolt-ci-docker-images/alpine-3.16

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - ci-scripts-tests
  - version-management
  - dependencies
  - build
  - test
  - publish
  - publish-artifacts

include:
  - local: "/.gitlab-ci/jobs/build/dependencies.yml"
  - local: "/.gitlab-ci/jobs/build/debian.yml"
  - local: "/.gitlab-ci/jobs/build/rpm.yml"
  - local: "/.gitlab-ci/jobs/test/ci_scripts.yml"
  - local: "/.gitlab-ci/jobs/test/packages.yml"
  - local: "/.gitlab-ci/jobs/publish/debian.yml"
  - local: "/.gitlab-ci/jobs/publish/rpm.yml"
  #- local: "/.gitlab-ci/jobs/publish/repo_backup_operations.yml"
  - local: "/.gitlab-ci/jobs/publish/releases/version_management.yml"
  - local: "/.gitlab-ci/jobs/publish/releases/notification_changelog.yml"
  - local: "/.gitlab-ci/jobs/publish/artifacts/docker.yml"
  - local: "/.gitlab-ci/jobs/publish/artifacts/vms.yml"
