#!/bin/sh
#
#  preinst
#
#  Debian package pre installation script
#
#  This script takes some important steps based on the installation responses.
#
#  To display response variables for debugging the installation:
#

set -e

. /usr/share/debconf/confmodule
#
# Parameters passed from apt install
deb_action=$1
deb_version=$2

###########################################
# Helper internal functions
###########################################

_echo() {
  [ -z "${VERBOSE}" ] || echo ">>> $1"
}


###########################################
# Script starts here
###########################################

_echo "entering preinst script: action=$1"

case "$deb_action" in

  upgrade)
    if [ "@PASSBOLT_FLAVOUR@" = "pro" ]; then
        su -c '/usr/share/php/passbolt/bin/cake passbolt subscription_check' -s /bin/bash www-data
    fi
    ;;


esac
