services:
  - registry.gitlab.com/passbolt/passbolt-ci-docker-images/dind:latest

.rules:
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^(snyk-fix*|feature\/debian\_*|master|release)/ || ($CI_COMMIT_BRANCH == "develop" && $CI_PIPELINE_SOURCE == "schedule")'
      when: on_success
    - if: '$CI_COMMIT_TAG == ""'
      #v3.9.0-rc.1-1-ce-debian
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+-\d+-$PASSBOLT_FLAVOUR-$PACKAGE_NAME/'
  before_script:
    - |
      mv debian/changelog{-$PASSBOLT_FLAVOUR,}
      mv rpm/CHANGELOG{-$PASSBOLT_FLAVOUR,}.md
      cd api
      cp -R ../* . || true

.dependencies:
  extends: .rules
  image: $PACKAGE_MANAGER_IMAGE
  stage: package-deps
  artifacts:
    paths:
      - $PACKAGE_MANAGER_PATH
    expire_in: 1 days
    when: on_success
  cache:
    paths:
      - $PACKAGE_MANAGER_PATH

composer:
  extends: .dependencies
  variables:
    PACKAGE_MANAGER_IMAGE: "registry.gitlab.com/passbolt/passbolt-ci-docker-images/composer:latest"
    PACKAGE_MANAGER_PATH: api/vendor/
  artifacts:
    paths:
      - api
  before_script:
    - git clone -b ${API_CLONE_BRANCH} https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/passbolt/passbolt-${PASSBOLT_FLAVOUR}-api.git api
  script:
    - |
      cd api
      composer install --prefer-dist -o --no-dev --ignore-platform-reqs --no-interaction

build-debian:
  extends: .rules
  image: registry.gitlab.com/passbolt/passbolt-ci-docker-images/debian-bullseye-11-slim:latest
  stage: package-build
  variables:
    PASSBOLT_COMPONENT: stable
  dependencies:
    - composer
  artifacts:
    paths:
      - "api/*.deb"
      - "api/*.build"
      - "api/*.buildinfo"
      - "api/*.changes"
    expire_in: 1 week
    when: on_success
  script:
    - |
      apt-get update
      apt-get install -y git-buildpackage devscripts apt-utils debconf-utils fakeroot equivs cdbs
      if [[ ! -z $NIGHTLY || $CI_COMMIT_BRANCH =~ ^(develop|feature\/debian\_*) ]]; then
        export PASSBOLT_COMPONENT=testing
        gbp dch --snapshot --snapshot-number=$(date +%s) --ignore-branch
      fi
      make -f debian/rules debian/control
      mk-build-deps -irt'apt-get --no-install-recommends -yV' debian/control
      dpkg-checkbuilddeps
      debuild --preserve-envvar PASSBOLT_FLAVOUR --preserve-envvar PASSBOLT_COMPONENT -us -uc -b -i -I
      cp ../*.deb .
      cp ../*.build .
      cp ../*.buildinfo .
      cp ../*.changes .

.publish-apt:
  image: registry.gitlab.com/passbolt/passbolt-ops/passbolt-aptly
  stage: publish
  dependencies:
    - build-debian
  script:
    - cd api && /publisher.sh
  retry:
    max: 0

.publish-debian:
  extends: .publish-apt
  variables:
    DISTRIBUTION: buster
    PREFIX: $PASSBOLT_FLAVOUR/debian
  needs:
    - job: "debian-buster-runtime"
    - job: "debian-buster-break"
    - job: "debian-buster-purge"
    - job: "debian-buster-fs"
    - job: "debian-bullseye-runtime"
    - job: "debian-bullseye-break"
    - job: "debian-bullseye-purge"
    - job: "debian-bullseye-fs"
    - job: "build-debian"

publish-debian-testing:
  extends: .publish-debian
  variables:
    PASSBOLT_COMPONENT: testing
    NIGHTLY: "true"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success

publish-debian-stable:
  extends: .publish-debian
  variables:
    PASSBOLT_COMPONENT: stable
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /publish-package/ && $CI_COMMIT_BRANCH == "release"'
      when: on_success

.publish-ubuntu:
  extends: .publish-apt
  variables:
    DISTRIBUTION: focal
    PREFIX: $PASSBOLT_FLAVOUR/ubuntu
  needs:
    - job: "ubuntu-2004-runtime"
    - job: "ubuntu-2004-break"
    - job: "ubuntu-2004-purge"
    - job: "ubuntu-2004-fs"
    # - job: "ubuntu-2204-runtime"
    # - job: "ubuntu-2204-break"
    # - job: "ubuntu-2204-purge"
    # - job: "ubuntu-2204-fs"
    - job: "build-debian"

publish-ubuntu-testing:
  extends: .publish-ubuntu
  variables:
    PASSBOLT_COMPONENT: testing
    PREFIX: $PASSBOLT_FLAVOUR/ubuntu
    NIGHTLY: "true"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success

publish-ubuntu-stable:
  extends: .publish-ubuntu
  variables:
    PASSBOLT_COMPONENT: stable
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /publish-package/ && $CI_COMMIT_BRANCH == "release"'
      when: on_success
