notify-changelog-change:
  image: registry.gitlab.com/passbolt/passbolt-ci-docker-images/debian-bullseye-11-slim:latest
  stage: package-deps
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
  script:
    - |
      apt-get update && apt-get install -y curl git
      if git diff --quiet HEAD\^ HEAD -- debian/changelog-ce debian/changelog-pro rpm/CHANGELOG-ce.md rpm/CHANGELOG-pro.md; then
        echo "No changes in changelogs"
      else
        source .gitlab-ci/scripts/bin/set-env.sh "$CI_COMMIT_TAG"
        echo "Sending slack changelog notification"
        echo "===================================="
        bash .gitlab-ci/scripts/bin/slack-status-messages.sh ":page_facing_up: NEW CHANGELOG COMMITED! $API_CLONE_BRANCH $PASSBOLT_FLAVOUR $PASSBOLT_COMPONENT" "$CI_PROJECT_URL/-/commit/$CI_COMMIT_SHA"
      fi
